= 1. Record architecture decisions

Date: 2018-08-27

== Status

Accepted

== Context

We need to record the architectural decisions made on this project.

== Decision

We will use Architecture Decision Records, as described by Michael Nygard in http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions[this article].
More ADR examples can be found in https://github.com/npryce/adr-tools/tree/master/doc/adr[Nat Pryce's Github].

We will add Alternatives to the regular format (Title, Status, Context, decision, Consequences).
We will also add decision criteria the way https://docs.arc42.org/tips/9-5/[arc42 suggests].

== Decision Criteria

[options="header",cols="1,2,2"]
|===
| ID            | Criterion                             | Importance
| C1            | Easy to use                           | must
| C2            | Minimal overhead                      | must
| C3            | Easily integrable into doctoolchain   | nice-to-have
|===


== Alternatives


[options="header",cols="1,2"]
|===
| Alternative           | Why problematic
| No doc, just agree.   | One week is enough to forget why something was done
| More process          | Too much overhead
|===

== Consequences

See Michael Nygard's article, linked above.